### ISSUE TITLE
Can't attach to a running process

### ISSUE THREAD

**Issue by avltree9798** [aktsk/ipa-medit#5]
I tried attaching to a running iOS game on my Apple Silicon Mac, but it always says that there's no process with the specified PID, eventho the process is there
```(base) ┌[testing@testing-MacBook-Pro] [/dev/ttys000]
└[~/Desktop]> ps aux | grep real
testing       9648   6.2  1.3 408670016 108624   ??  S     1:15PM   0:00.76 /private/var/folders/gk/yf10sxcx1g7fkv3hjw7r2lw40000gn/X/1AB061F8-0D8B-5E76-8319-26D335CFFD9F/d/Wrapper/realpolitiks.app/realpolitiks
testing       9661   0.0  0.0 408638592   1856 s000  S+    1:15PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox real
(base) ┌[testing@testing-MacBook-Pro] [/dev/ttys000]
└[~/Desktop]> ipa-medit -pid 9648
Please use `exit` or `Ctrl-D` to exit this program.
Target PID has been set to 9648.
2021/08/11 13:15:25 There is no process with the specified pid.
(base) ┌[testing@testing-MacBook-Pro] [/dev/ttys000] [1]
└[~/Desktop]> ps aux | grep real
testing       9648 188.7  2.9 408868192 241424   ??  R     1:15PM   0:14.14 /private/var/folders/gk/yf10sxcx1g7fkv3hjw7r2lw40000gn/X/1AB061F8-0D8B-5E76-8319-26D335CFFD9F/d/Wrapper/realpolitiks.app/realpolitiks
testing       9680   0.0  0.0 408646784   2016 s000  S+    1:15PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox real```

**Comment by tkmru** [comment]
Hmmm. I couldn't reproduce it in my environment.

**Comment by tkmru** [comment]
Parsing the result of `ps -ceo pid=,comm=` inside. What happens when you run this command in your environment?
https://github.com/aktsk/ipa-medit/blob/911032a6bd3813ef891fa7671de13bf02a23ab53/pkg/prompt/prompt.go#L166

**Comment by avltree9798** [comment]
I found my program up and running, but still can't attach
```
ps -ceo pid=,comm= | grep real
70884 realpolitiks
```

**Comment by tkmru** [comment]
What happens if you run it with the name option?

```
$ ./ipa-medit -name realpolitiks
```

**Comment by tkmru** [comment]
@avltree9798 I've tried to improve the command call, and I hope you'll try it with the latest version of the code.
[Improved command calls by tkmru · Pull Request #6 · aktsk/ipa-medit](https://github.com/aktsk/ipa-medit/pull/6)

**Comment by avltree9798** [comment]
The error is still there, so I decide to take a look at the source code, and I found something interesting. When I print the value of `line_pid` and `line_name`, sometimes the PID get assigned into `line_name` variable
```
                line := bytes.Split(scanner.Bytes(), []byte(" "))
		line_name := bytes.TrimSpace(line[1])
		line_pid := bytes.TrimSpace(line[0])
		fmt.Println(string(line_pid)+ " - "+string(line_name))
```

Output:
```
14423 - pbs
14424 - deleted
14425 - MTLCompilerService
14426 - MTLCompilerService
14427 - mdworker_shared
14428 - pidinfo
14454 - XprotectService
 - 4288
 - 4312
 - 4289
 - 4315
 - 4291
 - 4314
 - 4294
 - 4316
 - 4295
 - 4313
14429 - sudo
14430 - go
14453 - main
14455 - ps
```

And by changing the CheckPidExists logic to `if pid == string(line_pid) || pid == string(line_name) ` I can attach to the program, the only problem is it can't scan the memory, I think because it needs to be compiled into binary first and then codesigned the binary, but everytime I type `make build` it always returns 
```
└[~/test/ipa-medit]> make build
go build -o ipa-medit
# github.com/aktsk/ipa-medit
/opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64/link: /opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64/link: combining dwarf failed: unknown load command 0x80000034 (2147483700)
make: *** [build] Error 2
```

Do you know how to fix this? So I can validate my patch and create a PR for it

**Comment by avltree9798** [comment]
Compiling is success, so does the codesigning process, but the still can't scan the memory 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/16130362/129213883-dc5c36b5-770d-49c6-af60-4a461e63cce1.png">

**Comment by tkmru** [comment]
If you can't read the memory, it's probably because you can't resign it. You may also need to add an entitilement to enable debugging.
https://developer.apple.com/forums/thread/118450

**Comment by avltree9798** [comment]
We only need `com.apple.security.cs.debugger`, right?
Coz it's there
```
(base) ┌[avltree9798@Anthonys-MacBook-Pro] [/dev/ttys003] [1]
└[~]> pgrep ipa-medit
32006
(base) ┌[avltree9798@Anthonys-MacBook-Pro] [/dev/ttys003]
└[~]> codesign -d --entitlements :- 32006
Executable=/Users/avltree9798/anjay/ipa-medit/ipa-medit
Warning: Specifying ':' in the path is deprecated and will not work in a future release
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.cs.debugger</key><true/></dict></plist>%
```

**Comment by tkmru** [comment]
No, on macOS, the app to be debugged must also have an entitlement to enable debugging.

```
get-task-allow
```

SIP is the cause.
Have you already resigned the app you want to debug?
